import { useEffect, useState } from 'react'

type View = 'overview' | 'compare' | 'decoder' | 'fit' | 'problem'
type UniversityId = 'uos' | 'aus' | 'rit'
type Home = { id: string; name: string; area: string; rent: number; allIn: number; commute: number; score: number; color: string; emoji: string; tags: string[]; note: string }
type University = { id: UniversityId; name: string; shortName: string; city: string; campus: string; budget: number; commute: number; homes: Home[] }

const money = (value: number) => `AED ${value.toLocaleString('en-AE')}`
const universities: University[] = [
  { id: 'uos', name: 'University of Sharjah', shortName: 'UOS', city: 'Sharjah', campus: 'University City campus', budget: 3200, commute: 20, homes: [
    { id: 'aljada', name: 'Aljada Grove', area: 'Muwaileh Commercial', rent: 2200, allIn: 2860, commute: 14, score: 92, color: '#d9ebe4', emoji: '🌿', tags: ['Bills included', 'Shuttle nearby'], note: 'Calm, bright and close to campus.' },
    { id: 'university', name: 'University View', area: 'University City', rent: 2500, allIn: 3120, commute: 8, score: 88, color: '#e9dfd2', emoji: '☀️', tags: ['Gym included', '24/7 reception'], note: 'Social building with a short commute.' },
    { id: 'zahra', name: 'Al Zahra Rooms', area: 'Al Jazzat', rent: 1900, allIn: 2740, commute: 26, score: 79, color: '#e0e6f0', emoji: '🌤️', tags: ['Bigger rooms', 'Shared garden'], note: 'More space, but check the evening commute.' },
  ] },
  { id: 'aus', name: 'American University of Sharjah', shortName: 'AUS', city: 'Sharjah', campus: 'AUS campus, University City', budget: 3900, commute: 18, homes: [
    { id: 'muweilah', name: 'Muweilah Garden', area: 'Muwaileh', rent: 2800, allIn: 3540, commute: 12, score: 94, color: '#d9ebe4', emoji: '🌱', tags: ['Bills included', 'Study lounge'], note: 'A focused home with an easy campus run.' },
    { id: 'aljada-aus', name: 'Aljada Lofts', area: 'Aljada', rent: 3100, allIn: 3860, commute: 17, score: 87, color: '#e9dfd2', emoji: '☀️', tags: ['Pool access', 'Retail downstairs'], note: 'Lively community for an active routine.' },
    { id: 'naseem', name: 'Naseem House', area: 'Al Khan', rent: 2500, allIn: 3380, commute: 28, score: 76, color: '#e0e6f0', emoji: '🌤️', tags: ['Larger rooms', 'Waterfront'], note: 'More room, with a longer peak-time drive.' },
  ] },
  { id: 'rit', name: 'Rochester Institute of Technology Dubai', shortName: 'RIT Dubai', city: 'Dubai', campus: 'Dubai Silicon Oasis campus', budget: 4300, commute: 22, homes: [
    { id: 'silicon', name: 'Silicon Oasis Suites', area: 'Dubai Silicon Oasis', rent: 3200, allIn: 3920, commute: 9, score: 93, color: '#d9ebe4', emoji: '🌿', tags: ['Bills included', 'Campus shuttle'], note: 'A practical base minutes from RIT Dubai.' },
    { id: 'cedre', name: 'Cedre Residences', area: 'Dubai Silicon Oasis', rent: 3500, allIn: 4260, commute: 14, score: 86, color: '#e9dfd2', emoji: '☀️', tags: ['Gym included', 'Co-working space'], note: 'Comfortable, social and well connected.' },
    { id: 'warqa', name: 'Al Warqa Shared Home', area: 'Al Warqa', rent: 2700, allIn: 3610, commute: 25, score: 78, color: '#e0e6f0', emoji: '🌤️', tags: ['Bigger rooms', 'Quiet street'], note: 'Extra space at the cost of a longer commute.' },
  ] },
]

function Icon({ children }: { children: string }) { return <span className="icon" aria-hidden="true">{children}</span> }

export default function App() {
  const [view, setView] = useState<View>('overview')
  const [universityId, setUniversityId] = useState<UniversityId>(() => (localStorage.getItem('nestwise-university') as UniversityId) || 'uos')
  const [mobileNavOpen, setMobileNavOpen] = useState(false)
  const [setupOpen, setSetupOpen] = useState(false)
  const [tourOpen, setTourOpen] = useState(() => localStorage.getItem('nestwise-tour-seen') !== 'true')
  const [tourStep, setTourStep] = useState(0)
  const [compare, setCompare] = useState<string[]>([])
  const [bills, setBills] = useState(true)
  const [checklist, setChecklist] = useState([true, false, false, false])
  const [toast, setToast] = useState('')
  const university = universities.find(item => item.id === universityId) || universities[0]
  const homes = university.homes
  const current = homes[0]

  useEffect(() => { localStorage.setItem('nestwise-university', universityId); setCompare([homes[0].id, homes[1].id]) }, [universityId]) // eslint-disable-line react-hooks/exhaustive-deps
  const notify = (message: string) => { setToast(message); window.setTimeout(() => setToast(''), 2400) }
  const closeTour = () => { localStorage.setItem('nestwise-tour-seen', 'true'); setTourOpen(false); setTourStep(0) }
  const replayTour = () => { localStorage.removeItem('nestwise-tour-seen'); setTourStep(0); setTourOpen(true) }
  const nav = [{ id: 'overview' as View, label: 'Overview', icon: '⌂' }, { id: 'compare' as View, label: 'Compare homes', icon: '⇄' }, { id: 'decoder' as View, label: 'Lease decoder', icon: '▤' }, { id: 'fit' as View, label: 'Roommate & fit', icon: '♧' }, { id: 'problem' as View, label: 'Problem & Solution', icon: '◈' }]
  const toggleCompare = (id: string) => setCompare(prev => prev.includes(id) ? prev.filter(x => x !== id) : prev.length < 3 ? [...prev, id] : prev)

  return <div className="app-shell">
    <aside className={mobileNavOpen ? 'sidebar mobile-open' : 'sidebar'}>
      <div className="brand"><div className="brand-mark">n</div><span>nestwise</span><sup>beta</sup></div>
      <div className="profile-mini"><div className="avatar">AM</div><div><strong>Alex Morgan</strong><small>{university.city} · 2025/26</small></div><button aria-label="Profile menu">•••</button></div>
      <nav aria-label="Main navigation">{nav.map(item => <button key={item.id} className={view === item.id ? 'nav-item active' : 'nav-item'} onClick={() => { setView(item.id); setMobileNavOpen(false) }}><Icon>{item.icon}</Icon>{item.label}{item.id === 'compare' && <b className="nav-count">{compare.length}</b>}</button>)}</nav>
      <div className="sidebar-bottom"><div className="tip-card"><span className="sparkle">✦</span><strong>One more check</strong><p>Your shortlist is 1 detail away from being decision-ready.</p><button onClick={() => { setView('decoder'); notify('Opening your lease checklist') }}>Review checklist <span>→</span></button></div><button className="help-link" onClick={replayTour}><Icon>?</Icon>How nestwise works</button></div>
    </aside>
    <main className="main">
      <header className="topbar"><button className="mobile-menu" onClick={() => setMobileNavOpen(!mobileNavOpen)} aria-label={mobileNavOpen ? 'Close menu' : 'Open menu'} aria-expanded={mobileNavOpen}>☰</button><div className="breadcrumb">My housing plan <span>/</span> 2025–26</div><div className="top-actions"><button className="icon-button" onClick={() => notify('No new updates')} aria-label="Notifications">♢<i></i></button><button className="outline-btn" onClick={() => setSetupOpen(true)}>Edit setup <span>↗</span></button></div></header>
      <div className="content">
        {view === 'overview' && <Overview setView={setView} current={current} university={university} bills={bills} onNotify={notify} />}
        {view === 'compare' && <Compare homes={homes} compare={compare} toggleCompare={toggleCompare} bills={bills} setBills={setBills} onNotify={notify} />}
        {view === 'decoder' && <Decoder university={university} checklist={checklist} setChecklist={setChecklist} onNotify={notify} />}
        {view === 'fit' && <Fit university={university} onNotify={notify} />}
        {view === 'problem' && <Problem />}
      </div>
      <footer className="app-footer">Built with care by <strong>nestwise</strong> · <a href="https://www.linkedin.com/" target="_blank" rel="noreferrer">Visit the creator portfolio ↗</a><button onClick={replayTour}>Replay help tour</button></footer>
    </main>
    {setupOpen && <Setup university={university} onClose={() => setSetupOpen(false)} onDone={(id) => { setUniversityId(id); setSetupOpen(false); notify('Your AED housing plan is updated') }} />}
    {tourOpen && <Tour step={tourStep} setStep={setTourStep} onClose={closeTour} />}
    {toast && <div className="toast" role="status">✓ {toast}</div>}
  </div>
}

function Overview({ setView, current, university, bills, onNotify }: { setView: (v: View) => void; current: Home; university: University; bills: boolean; onNotify: (s: string) => void }) {
  const cost = bills ? current.allIn : current.rent + 420
  return <><section className="hero-row"><div><div className="eyebrow"><span className="live-dot"></span> YOUR HOUSING PLAN</div><h1>Make your next move<br /><em>with the full picture.</em></h1><p className="lede">A calmer way to compare student homes — beyond the headline rent.</p></div><div className="hero-note"><span>✦</span><div><strong>True Cost Lens</strong><p>What does this home really cost<br />you every month?</p></div></div></section>
    <section className="setup-banner"><div className="banner-icon">✎</div><div><strong>Your plan is based on {university.name}</strong><p>{money(university.budget)} monthly budget · {university.commute} min max commute · September move-in</p></div><button onClick={() => onNotify('Setup details are ready to edit')}>Edit details <span>→</span></button></section>
    <div className="section-heading"><div><h2>Good morning, Alex <span>✌</span></h2><p>Here’s where your shortlist stands today.</p></div><button className="text-btn" onClick={() => setView('compare')}>View all homes <span>→</span></button></div>
    <div className="metric-grid"><div className="metric-card feature"><div className="card-top"><span className="eyebrow">BEST VALUE MATCH</span><span className="match">{current.score}% match</span></div><div className="home-card-title"><div className="home-emoji" style={{ background: current.color }}>{current.emoji}</div><div><h3>{current.name}</h3><p>{current.area} · {current.commute} min to campus</p></div><button className="bookmark" aria-label="Save home" onClick={() => onNotify(`${current.name} saved`)}>♡</button></div><div className="cost-highlight"><div><small>true monthly cost</small><strong>{money(cost)}<sup>/mo</sup></strong></div><span className="pill green">within budget</span></div><div className="bar"><i style={{ width: '74%' }}></i></div><div className="card-footer"><span>Rent {money(current.rent)}</span><span>+ bills & hidden costs <b>{money(cost - current.rent)}</b></span></div><button className="primary-btn wide" onClick={() => setView('compare')}>See the full breakdown <span>→</span></button></div>
      <div className="metric-card budget-card"><div className="card-top"><span className="eyebrow">YOUR MONTHLY RANGE</span><button className="info" aria-label="About monthly range">i</button></div><div className="budget-number">{money(university.budget)} <small>/ month</small></div><div className="budget-visual"><span className="budget-pin" style={{ left: '68%' }}>{money(university.budget)}</span><div className="budget-track"><i></i></div><div className="track-labels"><span>{money(Math.round(university.budget * .7))}</span><span>{money(Math.round(university.budget * 1.25))}</span></div></div><p>3 homes fit your budget <span className="pill tiny green">on track</span></p><button className="secondary-btn" onClick={() => onNotify('Budget editor opened')}>Adjust budget <span>→</span></button></div>
      <div className="metric-card insight-card"><div className="card-top"><span className="eyebrow">A QUICK INSIGHT</span><span className="insight-icon">◒</span></div><h3>{money(600)} more rent can save you <em>4 hours</em> every week.</h3><div className="mini-compare"><div><b>{current.name}</b><span>{money(current.allIn)} · {current.commute} min</span></div><strong>vs</strong><div><b>{university.homes[2].name}</b><span>{money(university.homes[2].allIn)} · {university.homes[2].commute} min</span></div></div><p className="source"><span className="pill purple">Student-reported</span> 38 responses in {university.city}</p><button className="text-btn" onClick={() => setView('fit')}>Explore the tradeoff <span>→</span></button></div>
    </div>
    <section className="lower-grid"><div className="panel shortlist-panel"><div className="panel-heading"><div><h2>Your shortlist <span className="count-badge">3</span></h2><p>Sorted by your True Cost Lens score</p></div><button className="text-btn" onClick={() => setView('compare')}>Compare all <span>→</span></button></div>{university.homes.map((home, i) => <div className="shortlist-row" key={home.id}><span className="rank">0{i + 1}</span><div className="tiny-home" style={{ background: home.color }}>{home.emoji}</div><div className="row-name"><strong>{home.name}</strong><span>{home.area} · {home.commute} min</span></div><div className="row-cost"><strong>{money(home.allIn)}</strong><span>est. all-in</span></div><div className="score"><strong>{home.score}%</strong><span>match</span></div><button className="dots" aria-label={`${home.name} options`}>•••</button></div>)}</div><div className="panel next-panel"><div className="panel-heading"><div><h2>Next best action</h2><p>Keep your decision moving</p></div><span className="step-icon">2/4</span></div><div className="action-progress"><i style={{ width: '50%' }}></i></div><h3>Decode the lease before you book a viewing.</h3><p>We found 4 clauses worth checking in {current.name}’s listing.</p><button className="primary-btn" onClick={() => setView('decoder')}>Open lease decoder <span>→</span></button><div className="honesty"><span>◌</span><div><strong>Honesty over certainty</strong><p>We’ll always show what’s estimated vs. verified.</p></div></div></div></section>
    <div className="data-note"><span>ⓘ</span><span>Figures are estimates based on listing data and 38 student responses. Always verify with the landlord.</span><span className="pill amber">Data updated 2 days ago</span></div>
  </>
}

function Compare({ homes, compare, toggleCompare, bills, setBills, onNotify }: { homes: Home[]; compare: string[]; toggleCompare: (id: string) => void; bills: boolean; setBills: (v: boolean) => void; onNotify: (s: string) => void }) {
  const selected = homes.filter(h => compare.includes(h.id))
  return <><div className="page-title"><div><div className="eyebrow">DECIDE WITH CLARITY</div><h1>Compare the <em>whole story.</em></h1><p>Rent is just the starting line. Add the costs and tradeoffs that shape real student life.</p></div><button className="primary-btn" onClick={() => onNotify('Comparison link copied')}>Share shortlist ↗</button></div><div className="compare-toolbar"><div><strong>{selected.length} homes selected</strong><span> · Select up to 3</span></div><label className="switch-label"><span>Show true monthly cost</span><button className={bills ? 'switch on' : 'switch'} onClick={() => { setBills(!bills); onNotify('Cost view toggled') }} aria-label="Toggle true monthly cost"><i></i></button></label></div><div className="compare-grid">{homes.map(home => <article className={compare.includes(home.id) ? 'compare-card selected' : 'compare-card'} key={home.id}><div className="compare-image" style={{ background: home.color }}><span className="image-emoji">{home.emoji}</span><button className="select-check" onClick={() => toggleCompare(home.id)} aria-label={`Select ${home.name}`}>{compare.includes(home.id) ? '✓' : '+'}</button><span className="photo-label">Illustrative image</span></div><div className="compare-body"><div className="row-between"><span className="pill green">{home.score}% match</span><button className="bookmark" onClick={() => onNotify(`${home.name} saved`)}>♡</button></div><h2>{home.name}</h2><p className="muted">{home.area} · {home.commute} min to campus</p><div className="compare-price"><small>TRUE MONTHLY COST</small><strong>{money(bills ? home.allIn : home.rent)}<sup>/mo</sup></strong><span className="pill amber">Estimated</span></div><div className="cost-lines"><div><span>Rent</span><b>{money(home.rent)}</b></div><div><span>Bills & internet</span><b>{money(home.allIn - home.rent)}</b></div><div><span>Weekly commute</span><b>{money(home.commute <= 12 ? 100 : 260)}</b></div></div><div className="tag-row">{home.tags.map(t => <span key={t}>{t}</span>)}</div><button className="secondary-btn wide" onClick={() => onNotify(`Viewing request started for ${home.name}`)}>View home details <span>→</span></button></div></article>)}</div><div className="tradeoff-callout"><span className="callout-icon">↗</span><div><strong>The interesting tradeoff</strong><p>{homes[2].name} is {money(homes[2].allIn - homes[0].allIn)} more all-in, but gives you extra space. Is it worth a {homes[2].commute - homes[0].commute}-minute longer commute?</p></div><button className="text-btn" onClick={() => onNotify('Tradeoff added to your notes')}>Add to notes →</button></div></>
}

function Decoder({ university, checklist, setChecklist, onNotify }: { university: University; checklist: boolean[]; setChecklist: (v: boolean[]) => void; onNotify: (s: string) => void }) {
  const items = [{ title: 'Bills included — what exactly counts?', desc: 'Electricity, water, cooling and Wi-Fi may have fair-use caps.', tag: 'Needs verification', tone: 'coral' }, { title: 'Deposit protection scheme', desc: 'Ask how your deposit is documented and returned.', tag: 'Verified', tone: 'green' }, { title: 'Break clause & notice period', desc: 'Understand if you can leave early and what it costs.', tag: 'Check your contract', tone: 'amber' }, { title: 'Guarantor requirements', desc: 'Ask if an international or UAE-based guarantor is required.', tag: 'Student-reported', tone: 'purple' }]
  return <><div className="page-title"><div><div className="eyebrow">LEASE DECODER · {university.homes[0].name.toUpperCase()}</div><h1>Small print, <em>made human.</em></h1><p>Four questions to ask before you fall in love with a room.</p></div><div className="completion"><strong>{checklist.filter(Boolean).length}/4</strong><span>checked</span></div></div><div className="decoder-layout"><div className="panel clauses"><div className="panel-heading"><div><h2>Your check-in list</h2><p>Tap a clause to mark it ready.</p></div><span className="pill purple">Plain English</span></div>{items.map((item, i) => <button className={checklist[i] ? 'clause done' : 'clause'} key={item.title} onClick={() => { const next = [...checklist]; next[i] = !next[i]; setChecklist(next) }}><span className="clause-check">{checklist[i] ? '✓' : ''}</span><span className="clause-copy"><strong>{item.title}</strong><small>{item.desc}</small><span className={`pill ${item.tone}`}>{item.tag}</span></span><span className="clause-arrow">→</span></button>)}</div><div className="panel ask-panel"><span className="ask-orb">?</span><h2>Ask a better question.</h2><p>“Are bills included?” becomes more useful when you know what to ask next.</p><div className="question">“Does the fair-use cap cover summer cooling, and how is overage charged?” <button onClick={() => { navigator.clipboard?.writeText('Does the fair-use cap cover summer cooling, and how is overage charged?'); onNotify('Question copied') }}>Copy</button></div><span className="pill purple">Suggested question</span><div className="verified-box"><span>✓</span><div><strong>Verified by nestwise</strong><p>Based on UAE student housing guidance, 2025.</p></div></div></div></div><div className="data-note"><span>ⓘ</span><span>We explain patterns, not legal advice. Have your university housing team review anything unclear.</span><button className="text-btn" onClick={() => onNotify('Housing team contact copied')}>Contact housing team →</button></div></>
}

function Fit({ university, onNotify }: { university: University; onNotify: (s: string) => void }) {
  const [commute, setCommute] = useState(university.commute)
  const energy = commute <= 12 ? 'Your sweet spot' : commute <= 20 ? 'A considered tradeoff' : 'A stretch on busy days'
  return <><div className="page-title"><div><div className="eyebrow">LIFE FIT · {university.campus.toUpperCase()}</div><h1>How do you want<br />your week to <em>feel?</em></h1><p>The best home fits your routines, energy and people — not just your spreadsheet.</p></div><span className="pill green">Profile 78% complete</span></div><div className="fit-layout"><div className="panel commute-panel"><div className="panel-heading"><div><h2>Commute tradeoff</h2><p>Move the slider to feel the difference.</p></div><span className="commute-big">{commute}<small> min</small></span></div><div className="journey-art"><span>🏠</span><i style={{ width: `${Math.min(100, commute * 2.5)}%` }}></i><span>🎓</span></div><input aria-label="Commute minutes" type="range" min="5" max="45" value={commute} onChange={e => setCommute(Number(e.target.value))} /><div className="range-labels"><span>5 min · close</span><span>45 min · spacious</span></div><div className="tradeoff-result"><span className="result-face">{commute <= 12 ? '☀' : commute <= 20 ? '↔' : '◔'}</span><div><strong>{energy}</strong><p>{commute <= 12 ? 'More time for breakfast, societies and sleep.' : commute <= 20 ? 'You gain space, but spend more time in transit.' : 'That’s about 4 hours each week — worth pricing in.'}</p></div></div><button className="text-btn" onClick={() => onNotify('Commute preference saved')}>Save my preference →</button></div><div className="panel fit-questions"><div className="panel-heading"><div><h2>Your living rhythm</h2><p>Tell us what matters this year.</p></div><span>2/3</span></div>{[['☕','Quiet mornings','I like a calm start'],['♬','Social energy','I want people around'],['◌','My own space','I recharge alone']].map(([icon, title, sub], i) => <button className={i === 0 ? 'fit-option selected' : 'fit-option'} key={title} onClick={() => onNotify(`${title} preference selected`)}><span className="fit-icon">{icon}</span><span><strong>{title}</strong><small>{sub}</small></span><span className="radio">{i === 0 ? '✓' : ''}</span></button>)}<button className="secondary-btn wide" onClick={() => onNotify('Lifestyle preferences saved')}>Save preferences <span>→</span></button></div></div><div className="fit-bottom"><div><span className="pill purple">Student-reported</span><strong> 71% of students say commute affects where they study.</strong></div><button className="text-btn" onClick={() => onNotify('Source details opened')}>See the source →</button></div></>
}

function Problem() { return <><div className="problem-hero"><div><div className="eyebrow">THE WHY BEHIND NESTWISE</div><h1>House hunting is a<br /><em>math problem</em> in disguise.</h1><p>Students are asked to make a high-stakes decision with incomplete information, hidden costs and a deadline. nestwise turns noise into a confident next step.</p></div><div className="problem-stamp">✦<span>DESIGΝ<br />ATHON<br />2025</span></div></div><div className="problem-grid"><div className="problem-card pain"><span className="big-number">01</span><h2>The problem</h2><p>Listings optimise for a single number: rent. Students pay for the rest in surprises, time and stress.</p><div className="stat-row"><strong>AED 740</strong><span>average monthly costs<br />missed by headline rent</span></div></div><div className="problem-card solution"><span className="big-number">02</span><h2>The solution</h2><p>One honest lens for the whole decision: true cost, real tradeoffs and questions worth asking.</p><div className="solution-list"><span>✓ See the all-in monthly cost</span><span>✓ Compare time, space and money</span><span>✓ Decode before you commit</span></div></div></div><div className="principles"><div><span>01</span><strong>Honesty over certainty</strong><p>Every number tells you where it came from.</p></div><div><span>02</span><strong>Progress over overwhelm</strong><p>One clear next action, not another spreadsheet.</p></div><div><span>03</span><strong>Agency over anxiety</strong><p>You decide what “worth it” means.</p></div></div></> }

function Setup({ university, onClose, onDone }: { university: University; onClose: () => void; onDone: (id: UniversityId) => void }) {
  const [step, setStep] = useState(1)
  const [selected, setSelected] = useState<UniversityId>(university.id)
  return <div className="modal-backdrop"><div className="setup-modal" role="dialog" aria-modal="true" aria-labelledby="setup-title"><button className="modal-close" onClick={onClose} aria-label="Close">×</button><div className="setup-progress"><i style={{ width: `${step * 33.3}%` }}></i></div><div className="setup-kicker">LET’S MAKE THIS PERSONAL · 0{step}/03</div>{step === 1 && <><h2 id="setup-title">Where are you<br /><em>headed?</em></h2><p>Choose your university and we’ll tune campus, commute and housing context.</p><label>University<select value={selected} onChange={e => setSelected(e.target.value as UniversityId)}>{universities.map(item => <option key={item.id} value={item.id}>{item.shortName} · {item.name}</option>)}</select></label><label>Move-in month<select defaultValue="September"><option>September 2025</option><option>January 2026</option></select></label></>}{step === 2 && <><h2>What feels<br /><em>comfortable?</em></h2><p>A real budget is more than a rent ceiling.</p><label>Monthly all-in budget <div className="input-prefix"><span>AED</span><input defaultValue={university.budget} type="number" /></div></label><label>Maximum commute <div className="input-prefix"><input defaultValue={university.commute} type="number" /><span>minutes</span></div></label></>}{step === 3 && <><h2>What makes a<br /><em>good week?</em></h2><p>Pick the things you’ll notice every day.</p><div className="setup-options"><button className="selected">☕ Quiet mornings</button><button>♬ Social energy</button><button className="selected">◌ My own space</button><button>♧ Near green space</button></div></>}<div className="modal-actions"><button className="text-btn" onClick={step === 1 ? onClose : () => setStep(step - 1)}>{step === 1 ? 'Not now' : '← Back'}</button><button className="primary-btn" onClick={step === 3 ? () => onDone(selected) : () => setStep(step + 1)}>{step === 3 ? 'Build my plan' : 'Continue →'}</button></div></div></div>
}

function Tour({ step, setStep, onClose }: { step: number; setStep: (n: number) => void; onClose: () => void }) {
  const slides = [{ title: 'Welcome to nestwise', text: 'Compare real student homes with the full monthly picture — not just the headline rent.' }, { title: 'Choose your context', text: 'Pick UOS, AUS or RIT Dubai to update campus, commute and realistic UAE housing examples.' }, { title: 'Make progress, calmly', text: 'Use the decoder and life-fit tools to turn uncertainty into your next clear step.' }]
  const slide = slides[step]
  return <div className="modal-backdrop tour-backdrop"><div className="setup-modal tour-modal" role="dialog" aria-modal="true" aria-labelledby="tour-title"><button className="modal-close" onClick={onClose} aria-label="Dismiss walkthrough">×</button><div className="ask-orb">✦</div><div className="setup-kicker">NESTWISE WALKTHROUGH · 0{step + 1}/03</div><h2 id="tour-title">{slide.title}</h2><p>{slide.text}</p><div className="tour-dots">{slides.map((_, i) => <i key={i} className={i === step ? 'active' : ''}></i>)}</div><div className="modal-actions"><button className="text-btn" onClick={onClose}>Skip</button><button className="primary-btn" onClick={() => step === slides.length - 1 ? onClose() : setStep(step + 1)}>{step === slides.length - 1 ? 'Start exploring' : 'Next →'}</button></div></div></div>
}
